version: '3'
services:
    nginx:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8080:80
        networks:
            - app_net
        depends_on:
            - backend
        volumes:
            - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: always
        command: /bin/sh -c "php artisan key:generate && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
        volumes:
            - .env:/var/www/html/.env
        networks:
            - app_net
        depends_on:
            - db

    db:
        image: 'mysql/mysql-server:8.0'
        volumes:
            - app-db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        networks:
            - app_net
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

networks:
    app_net:
        driver: bridge

volumes:
    app-db:
        driver: local